# # Version 3.0
# services:
#   seq:
#     image: datalust/seq:latest
#     container_name: MedicalOfficeSeq
#     environment:
#       - ACCEPT_EULA=Y
#     ports:
#       - "5341:80"
#     networks:
#       medicalnetwork:
#         ipv4_address: 192.168.1.100
#     restart: always

#   sql1:
#     container_name: MedicalOfficeSql
#     image: mcr.microsoft.com/mssql/server:latest
#     environment:
#       - ACCEPT_EULA=Y
#       - SA_PASSWORD=Cbmwjmkq23
#     ports:
#       - "1433:1433"
#     volumes:
#       - sql_data:/var/opt/mssql
#     networks:
#       medicalnetwork:
#         ipv4_address: 192.168.1.102
#     restart: always

#   medicalofficeapi:
#     build:
#       context: .
#       dockerfile: './Dockerfile'
#     container_name: MedicalOfficeWebApi
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Production # Cambia a Development si es necesario
#     ports:
#       - "8080:8080"
#       - "8081:8081"
#     networks:
#       medicalnetwork:
#         ipv4_address: 192.168.1.101
#     depends_on:
#       - seq
#     restart: always

#   frontend:
#     build:
#       context: '../Medical.Office.ReactWebClient/'
#       dockerfile: Dockerfile
#       args:
#       - NEXT_PUBLIC_API_URL=http://MedicalOfficeWebApi:8080
#     container_name: MedicalOfficeWebClient
#     environment:
#       - NEXT_PUBLIC_API_URL=http://MedicalOfficeWebApi:8080
#     ports:
#       - "3000:80"
#     networks:
#       medicalnetwork:
#         ipv4_address: 192.168.1.103
#     depends_on:
#       - medicalofficeapi
#     restart: always

# networks:
#   medicalnetwork:
#     external:
#       name: medicalnetwork

# volumes:
#   sql_data:

# 4.0
version: '3.0'
services:

  sql1:
    container_name: medicalofficesql
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Cbmwjmkq23
    ports:
      - "1433:1433"
    volumes:
      - medical_office_sql_data:/var/opt/mssql
    restart: always

  seq:
    image: datalust/seq:latest
    container_name: MedicalOfficeSeq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    depends_on:
      - sql1
    restart: always

  medicalofficeapi:
    build:
      context: .
      dockerfile: './Dockerfile'
    container_name: medicalofficewebapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sql1
      - seq
    restart: always

  frontend:
    build:
      context: '../Medical.Office.ReactWebClient/'
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
    container_name: medicalofficewebclient
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - medicalofficeapi
    restart: always

volumes:
  medical_office_sql_data:
