version: '3.8'
services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    networks:
      - medicalnetwork
    restart: always

  medicalofficeapi:
    build:
      context: .  # Usamos el directorio actual como contexto
      dockerfile: "./Medical.Office.Net8WebApi/Dockerfile"  # Apunta al Dockerfile en el directorio actual
    container_name: MedicalOfficeApi
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - medicalnetwork
    depends_on:
      - seq
    restart: always

  sql1:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server:latest  # Ejemplo de imagen de SQL Server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Cbmwjmkq23
    ports:
      - "1433:1433"
    networks:
      - medicalnetwork
    restart: always

networks:
  medicalnetwork:
    external: true
# Configuración de volúmenes y persistencia (opcional)
volumes:
  seq_data:
  sql_data:
