# Directo
@Medical.Office.Net8WebApi_HostAddress = http://localhost:5038

# IIS Express
#@Medical.Office.Net8WebApi_HostAddress = http://localhost:14025

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/registerusers
Content-Type: application/json

{
  "usr": "Doctor",
  "psswd": "Doctor123*",
  "name": "Admin",
  "lastname": "System",
  "role": "Doctor",
  "position": "Doctor",
  "specialtie": "Cirujano"
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/login
Content-Type: application/json

{
  "usr": "Admin",
  "psswd": "Admin123*"
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertposition/{Administrador}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertspecialties/{Administrador}

###
