@Medical.Office.Net8WebApi_HostAddress = http://localhost:5038

PUT {{Medical.Office.Net8WebApi_HostAddress}}/api/ActualizarProducto/{ProductoID}
Content-Type: application/json

{
  //ActualizarProductoRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/ActualizarStock/{ProductoID}
Content-Type: application/json

{
  //ActualizarStockRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/AgregarProducto
Content-Type: application/json

{
  //AgregarProductoRequestBody
}

###

@FileID=0
DELETE {{Medical.Office.Net8WebApi_HostAddress}}/api/DeletePatientFile/{IDPatient}/{{FileID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/getrandomnumber

###

@corteID=0
DELETE {{Medical.Office.Net8WebApi_HostAddress}}/api/EliminarCorte/{{corteID}}

###

@ProductoID=0
DELETE {{Medical.Office.Net8WebApi_HostAddress}}/api/EliminarProducto/{{ProductoID}}

###

@VentaID=0
DELETE {{Medical.Office.Net8WebApi_HostAddress}}/api/EliminarVenta/{{VentaID}}

###

@PatientID=0
GET {{Medical.Office.Net8WebApi_HostAddress}}/api/getactivemedications/{{PatientID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/getallconfigurations

###

@IDDoctor=0
GET {{Medical.Office.Net8WebApi_HostAddress}}/api/GetDoctors/{{IDDoctor}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/getfamilyhistory/{{PatientID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/getmedicalhistorynotes/{{PatientID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/GetNonPathologicalHistory/{{PatientID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/GetPathologicalBackground/{{PatientID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/GetPatientAllergies/{{PatientID}}

###

@IDPatient=0
GET {{Medical.Office.Net8WebApi_HostAddress}}/api/PatientData/{{IDPatient}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/GetPatientDataAndAntecedents/{{IDPatient}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/GetPatientFile/{IDPatient}/{{FileID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/GetPsychiatricHistory/{{PatientID}}

###

@id=0
@usr=string
GET {{Medical.Office.Net8WebApi_HostAddress}}/api/UsersData?id={{id}}&usr={{usr}}
Authorization: Bearer {{$bearerToken}}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertactivemedications
Content-Type: application/json

{
  //InsertActiveMedicationsRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/InsertDoctor
Content-Type: application/json

{
  //InsertDoctorsRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertfamilyhistory
Content-Type: application/json

{
  //InsertFamilyHistoryRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/InsertMedicalAppointmentCalendar
Content-Type: application/json

{
  //InsertMedicalAppointmentCalendarRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/InsertMedicalHistoryNotes
Content-Type: application/json

{
  //InsertMedicalHistoryNotesRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/InsertNonPathologicalHistory
Content-Type: application/json

{
  //InsertNonPathologicalHistoryRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertofficesetup
Content-Type: application/json

{
  //InsertOfficeSetupRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/InsertPathologicalBackground
Content-Type: application/json

{
  //InsertPathologicalBackgroundRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/InsertPatientAllergies
Content-Type: application/json

{
  //InsertPatientAllergiesRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertpatient
Content-Type: application/json

{
  //InsertPatientDataRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/UploadPatientFile
Content-Type: application/json

{
  //InsertPatientFileRequestBody
}

###

@Position=string
POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertposition/{{Position}}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertpsychiatricHistory
Content-Type: application/json

{
  //InsertPsychiatricHistoryRequestBody
}

###

@Specialtie=string
POST {{Medical.Office.Net8WebApi_HostAddress}}/api/insertspecialties/{{Specialtie}}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/login
Content-Type: application/json

{
  //LoginUsersRequestBody
}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerCortePorId/{{corteID}}

###

@fechaInicio=2024-12-23T09:15:22.3404957+00:00
@fechaFin=2024-12-23T09:15:22.3404957+00:00
GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerCortesPorRango?fechaInicio={{fechaInicio}}&fechaFin={{fechaFin}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerDetalleDeVentas/{{ventaID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerProductoPorId/{{ProductoID}}

###

@LimiteStock=0
GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerProductosConBajoStock?LimiteStock={{LimiteStock}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerResumenDeCortesPorDia?fechaInicio={{fechaInicio}}&fechaFin={{fechaFin}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerTodosLosCortes

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerTodosLosProductos

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerVentaPorId/{{VentaID}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerVentasPorDia?fechaInicio={{fechaInicio}}&fechaFin={{fechaFin}}

###

GET {{Medical.Office.Net8WebApi_HostAddress}}/api/ObtenerVentasPorRango?FechaInicio={{FechaInicio}}&FechaFin={{FechaFin}}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/registerusers
Authorization: Bearer {{$bearerToken}}
Content-Type: application/json

{
  //RegisterUsersRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/RegistrarCorte
Content-Type: application/json

{
  //RegistrarCorteRequestBody
}

###

POST {{Medical.Office.Net8WebApi_HostAddress}}/api/RegistrarVenta
Content-Type: application/json

{
  //RegistrarVentaRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdateActiveMedications/{IdPatient}
Content-Type: application/json

{
  //UpdateActiveMedicationsRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/updateDoctor/{IDDoctor}
Content-Type: application/json

{
  //UpdateDoctorsRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdateFamilyHistory/{IdPatient}
Content-Type: application/json

{
  //UpdateFamilyHistoryRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdateLaboralDays/{Id}
Content-Type: application/json

{
  //UpdateLaboralDaysRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdateMedicalHistoryNotes/{IdPatient}
Content-Type: application/json

{
  //UpdateMedicalHistoryNotesRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdateNonPathologicalHistory/{IdPatient}
Content-Type: application/json

{
  //UpdateNonPathologicalHistoryRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdateOfficeSetup
Content-Type: application/json

{
  //UpdateOfficeSetupRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdatePathologicalBackground/{IdPatient}
Content-Type: application/json

{
  //UpdatePathologicalBackgroundRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdatePatientAllergies/{IdPatient}
Content-Type: application/json

{
  //UpdatePatientAllergiesRequestBody
}

###

PATCH {{Medical.Office.Net8WebApi_HostAddress}}/api/UpdatePsychiatricHistory/{IdPatient}
Content-Type: application/json

{
  //UpdatePsychiatricHistoryRequestBody
}

###
